---
server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: postgres
    password: 5683
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update